# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomusermodel',
            name='ice_sdp',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='roomusermodel',
            name='ice_sdp_mid',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='roomusermodel',
            name='sdp_description',
            field=models.CharField(max_length=2000),
        ),
    ]
