# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0002_auto_20170412_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('is_initiator', models.IntegerField(default=0)),
                ('ice_sdp_mid', models.CharField(max_length=2000)),
                ('ice_sdp', models.CharField(max_length=2000)),
                ('ice_sdp_m_line_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SdpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('is_initiator', models.IntegerField(default=0)),
                ('sdp_type', models.CharField(max_length=50)),
                ('sdp_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomUserModel',
        ),
    ]
