# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0004_icemodel_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdpmodel',
            name='sdp_description',
            field=models.CharField(max_length=5000),
        ),
    ]
