# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0005_auto_20170413_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('src_user_id', models.IntegerField(default=0)),
                ('dst_user_id', models.IntegerField(default=0)),
                ('is_initiator', models.IntegerField(default=0)),
                ('ice_sdp_mid', models.CharField(max_length=2000)),
                ('ice_sdp', models.CharField(max_length=2000)),
                ('ice_sdp_m_line_index', models.IntegerField(default=0)),
                ('is_added', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='IceModel',
        ),
        migrations.AddField(
            model_name='sdpmodel',
            name='dst_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sdpmodel',
            name='src_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
