# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward', '0006_auto_20170414_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdpmodel',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
